version: "3.8"

services:
  db:
    image: postgres
    container_name: go-postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./_pg_data:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: "redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass passw0rd
    ports:
      - 6379:6379
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf

  webapi:
    container_name: web-api
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ".:/app"
    restart: always
    depends_on:
      - db
      - redis
    links:
      - "db:database"

  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapi
